parameters:
    serializer.config:
        serialize_handlers: true
        serialize_subscribers: true

services:
    flow.network:
        class: FlowUI\Component\Network
        factory: ['@flow.network.factory', 'create']
        arguments:
            - '@flow.network.map'

    flow.network.factory:
        class: FlowUI\Component\Network\Factory
        arguments:
            - '@flow.parser'

    flow.network.map:
        class: FlowUI\Component\Network\Map
        public: false
        arguments:
            - [] # registerHandlers compiler pass
            - [] # registerSubscribers compiler pass

    flow.parser:
        public: false
        class: FlowUI\Component\Parser\Parser

    flow.serializer:
        class: FlowUI\Component\Serializer\D3ForceLayoutSerializer
        arguments:
            - '%serializer.config%'

    flow.validator:
        class: FlowUI\Component\Validator\Validator
        arguments:
            - ['@flow.validator.constraint.handler_triggers_command', '@flow.validator.constraint.event_without_subscriber']
    # todo service discovery
    flow.validator.constraint.handler_triggers_command:
        class: FlowUI\Component\Validator\Constraint\HandlerTriggersCommand
        public: false

    flow.validator.constraint.event_without_subscriber:
        class: FlowUI\Component\Validator\Constraint\EventWithoutSubscriber
        public: false