services:
    test_service:
        class: FlowUI\FlowBundle\Service\TestService
        arguments:
            - [] # registerHandlers compiler pass
            - [] # registerSubscribers compiler pass

    flow.validator:
        class: FlowUI\Component\Validator\Validator
        arguments:
            - ['@flow.validator.constraint.handler_triggers_command', '@flow.validator.constraint.event_without_subscriber']

    flow.validator.constraint.handler_triggers_command:
        class: FlowUI\Component\Validator\Constraint\HandlerTriggersCommand
        public: false

    flow.validator.constraint.event_without_subscriber:
        class: FlowUI\Component\Validator\Constraint\EventWithoutSubscriber
        public: false
