services:
    test_service:
        class: FlowUI\FlowBundle\Service\TestService
        arguments:
            - [] # registerHandlers compiler pass
            - [] # registerSubscribers compiler pass
