parameters:
    serializer.config:
        display_handlers: true
        display_subscribers: true

services:
    flow.network.factory:
        class: FlowUI\Component\Network\Factory
        arguments:
            - '@flow.network.command_handler_map'
            - '@flow.network.event_subscribers_map'

    flow.validator:
        class: FlowUI\Component\Validator\Validator
        arguments:
            - ['@flow.validator.constraint.handler_triggers_command', '@flow.validator.constraint.event_without_subscriber']

    flow.validator.constraint.handler_triggers_command:
        class: FlowUI\Component\Validator\Constraint\HandlerTriggersCommand
        public: false

    flow.validator.constraint.event_without_subscriber:
        class: FlowUI\Component\Validator\Constraint\EventWithoutSubscriber
        public: false

    flow.network.command_handler_map:
        class: FlowUI\Component\Network\CommandHandlerMap
        arguments:
            - [] # registerHandlers compiler pass

    flow.network.event_subscribers_map:
        class: FlowUI\Component\Network\EventSubscribersMap
        arguments:
            - [] # registerSubscribers compiler pass

    flow.serializer:
        class: FlowUI\Component\Serializer\D3ForceLayoutSerializer
        arguments:
            - '%serializer.config%'
