parameters:
    mapper.config:
        map_handlers: true
        map_subscribers: true

services:
    flow.mapper:
        alias: 'flow.mapper.d3.force_layout_mapper'

    flow.mapper.d3.force_layout_mapper:
        class: Flow\Mapper\D3\ForceLayoutMapper
        arguments:
            - '%mapper.config%'

    flow.network:
        class: Flow\Network\Network
        factory: ['@flow.network.factory', 'create']
        arguments:
            - '@flow.network.map'

    flow.network.factory:
        class: Flow\Network\Factory
        arguments:
            - '@flow.parser.messages_used'

    flow.network.map:
        class: Flow\Network\Map
        public: false
        arguments:
            - [] # registerHandlers compiler pass
            - [] # registerSubscribers compiler pass

    flow.parser:
        class: Flow\Parser\Parser
        abstract: true
        arguments:
            - '@flow.vendor.php_parser.factory'
            - '@flow.vendor.php_parser.node_traverser'

    flow.parser.messages_used:
        parent: flow.parser
        calls:
            - [setVisitor, ['@flow.parser.visitor.messages_used']]

    flow.parser.visitor.messages_used:
        class: Flow\Parser\Visitor\MessagesUsedNodeVisitor
        public: false

    flow.vendor.php_parser.factory:
        class: PhpParser\ParserFactory
        public: false

    flow.vendor.php_parser.node_traverser:
        class: PhpParser\NodeTraverser
        public: false

    flow.validator:
        class: Flow\Validator\Validator
        arguments:
            - ['@flow.validator.constraint.handler_triggers_command', '@flow.validator.constraint.event_without_subscriber']

    # todo: service discovery

    flow.validator.constraint.handler_triggers_command:
        class: Flow\Validator\Constraint\HandlerTriggersCommand
        public: false

    flow.validator.constraint.event_without_subscriber:
        class: Flow\Validator\Constraint\EventWithoutSubscriber
        public: false