parameters:
    mapper.config:
        map_handlers: true
        map_subscribers: true

services:
    flow.mapper:
        alias: 'flow.mapper.d3.force_layout_mapper'

    flow.mapper.d3.force_layout_mapper:
        class: Flow\Mapper\D3\ForceLayoutMapper
        arguments:
            - '%mapper.config%'

    flow.network:
        class: Flow\Network\Network
        factory: ['@flow.network.factory', 'create']

    flow.network.factory:
        class: Flow\Network\Factory
        public: false
        calls:
            - [addStep, ['@flow.network.factory.step.add_commands_and_handlers']]
            - [addStep, ['@flow.network.factory.step.add_events_and_subscribers']]
            - [addStep, ['@flow.network.factory.step.add_published_messages']]

    flow.network.factory.step.add_commands_and_handlers:
        class: Flow\Network\Factory\Step\AddCommandsAndHandlers
        public: false
        arguments:
            - '%flow.map.command_handler%' # registerHandlers compiler pass

    flow.network.factory.step.add_events_and_subscribers:
        class: Flow\Network\Factory\Step\AddEventsAndSubscribers
        public: false
        arguments:
            - '%flow.map.events_subscribers%' # registerSubscribers compiler pass

    flow.network.factory.step.add_published_messages:
        class: Flow\Network\Factory\Step\AddPublishedMessages
        public: false
        arguments:
            - '@flow.collector.messages_used'

    flow.collector:
        class: Flow\Collector\Collector
        abstract: true
        arguments:
            - '@flow.vendor.php_parser.factory'
            - '@flow.vendor.php_parser.node_traverser'
            - '@flow.collector.source_code_reader'

    flow.collector.messages_used:
        parent: flow.collector
        calls:
            - [setVisitor, ['@flow.collector.visitor.messages_used']]

    flow.collector.visitor.messages_used:
        class: Flow\Collector\Parser\Visitor\MessagesUsedNodeVisitor
        public: false

    flow.collector.source_code_reader:
        class: Flow\Collector\Reader\SourceCodeReader
        public: false
        arguments:
            - '@flow.collector.file_reader'

    flow.collector.file_reader:
        class: Flow\Collector\Reader\FileReader
        public: false

    flow.vendor.php_parser.factory:
        class: PhpParser\ParserFactory
        public: false

    flow.vendor.php_parser.node_traverser:
        class: PhpParser\NodeTraverser
        public: false

    flow.validator:
        class: Flow\Validator\Validator

    flow.validator.constraint.handler_triggers_command:
        class: Flow\Validator\Constraint\HandlerTriggersCommand
        public: false
        tags:
            - { name: flow.validator_constraint }

    flow.validator.constraint.event_without_subscriber:
        class: Flow\Validator\Constraint\EventWithoutSubscriber
        public: false
        tags:
            - { name: flow.validator_constraint }